# Generated by Django 4.2 on 2023-04-27 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_admin_delete_artist_remove_user_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
        migrations.AddField(
            model_name='song',
            name='users_favorite',
            field=models.ManyToManyField(related_name='favorite_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, upload_to='images/profiles/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images/covers/'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
