# Generated by Django 4.2 on 2023-04-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_song_user_song_users_favorite_user_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='mood',
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cover', models.ImageField(blank=True, upload_to='images/covers/')),
                ('songs', models.ManyToManyField(related_name='moods', to='api.song')),
            ],
        ),
    ]
