# Generated by Django 4.2 on 2023-04-27 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_song_mood_mood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_bpm',
            new_name='bpm',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_link',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(blank=True, default=19, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='link',
            field=models.FileField(blank=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='users_favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
