# Generated by Django 4.2 on 2023-04-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_song_bpm_song_bpm_remove_song_song_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='bpm',
        ),
        migrations.RemoveField(
            model_name='song',
            name='language',
        ),
        migrations.RemoveField(
            model_name='song',
            name='scale',
        ),
        migrations.AddField(
            model_name='song',
            name='danceability',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='energy',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='instrumentalness',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='key',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='liveness',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='loudness',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='mode',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='speechiness',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='tempo',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='time_signature',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='valence',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
