# Generated by Django 4.2 on 2023-04-29 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_song_danceability_alter_song_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='users_favorite',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
