# Generated by Django 4.2 on 2023-04-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_song_artist_alter_song_users_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='camelot',
            field=models.TextField(default='3B', max_length=255),
            preserve_default=False,
        ),
    ]
