# Generated by Django 4.2 on 2023-05-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_mood_songs_remove_song_users_favorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='isDeleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mood',
            name='isDeleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='remix',
            name='isDeleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='request',
            name='isDeleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='song',
            name='isDeleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='isDeleted',
            field=models.BooleanField(default=True),
        ),
    ]
