# Generated by Django 4.2 on 2023-05-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_favorites_isdeleted_mood_isdeleted_remix_isdeleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remix',
            name='link',
            field=models.FileField(blank=True, upload_to='mix/'),
        ),
    ]
