# Generated by Django 4.2 on 2023-05-08 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remix_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='remix',
            name='mood',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='api.mood'),
            preserve_default=False,
        ),
    ]
