# Generated by Django 4.2 on 2023-05-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remix_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='remix',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=10, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
