# Generated by Django 4.2 on 2023-05-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remix_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='high_danceability',
            field=models.DecimalField(blank=True, decimal_places=10, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mood',
            name='low_danceability',
            field=models.DecimalField(blank=True, decimal_places=10, default=0.0, max_digits=15),
            preserve_default=False,
        ),
    ]
