# Generated by Django 4.2 on 2023-05-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_mood_high_danceability_mood_low_danceability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30),
        ),
    ]
